### PR TITLE
add comment of build time to code

### PR DESCRIPTION
**Pull request by dimohamdy**
add comment of build time to code with when check value of add comment checkBox

### CODE REVIEW

**Comment by RobertGummesson** [comment]
Closing this one due to two reasons:
- It's not clear what the checkbox does. What am I adding a comment to?
- Once it's checked, an error occurs when a table view row is clicked:
" fatal error: Array index out of range"

**Comment by dimohamdy** [comment]
@RobertGummesson 
it's add comment to top of method "//Build Time for this method is 575.4 ms " when click cell of table and the check box selected

**Comment by RobertGummesson** [comment]
@dimohamdy 
1 - Right. The issue I feel is that the checkbox is not self explanatory. I wasn't quite sure what it meant until you explained it now. Not sure what to do instead though. I'd like the app to be clear and simple to use.
2 - I can't share the project with you (closed source) but the issue is that the line breaks for it are '\n' and not '\r\n'.

**Comment by dimohamdy** [comment]
@RobertGummesson  i will fix the bug in point 2 ASAP , i want to help developer to not open app an check the method i want him to know the build time of method at once

**Pull request closed without merging**
