### PR TITLE
Dato/keeping focus after open file

### PR DESCRIPTION
**Pull request by horse304**

### CODE REVIEW

**Comment by RobertGummesson** [comment]
I prefer to keep the existing solution for going to the line number. Although my solution isn't perfect either. My reasons are:
- The current code uses a notification observer instead of waiting for 0.2s. 
- The current code uses String instead of NSString

Having that said, I like the idea of keeping the focus on the plugin window. If you would submit a PR with only that change, I’d accept it. 

The header idea is promising too. The dependency of valueForKeyPath isn't great in the current code.

**Comment by horse304** [comment]
I tried to submit the code of keeping focus only, but with your solution I don't found any way to handle the case of the file path is already opened.
Ex: I want to switch between `TokenInputView.swift:40:30` and `TokenInputView.swift:45:20`. With your solution, the notification `IDESourceCodeEditorDidFinishSetup` is not fired.

**Comment by RobertGummesson** [comment]
That is very true. I will attempt to fix that though. My thinking is we check what file is already open. If it's the same file, then we only jump to the line. If not, then we subscribe to  IDESourceCodeEditorDidFinishSetup and call openFile just as now.

I'm aware it's a bit hacky to subscribe to the notification as it is now given it may not be called but hopefully the file check part won't be too hard to work out. We'll see. :)

**Comment by RobertGummesson** [comment]
@horse304 - Worked out how to do it. 'Go to line' now works with files that are opened too.

**Comment by horse304** [comment]
Nice, thanks @RobertGummesson

**Comment by horse304** [comment]
Have a nice week!

**Pull request closed without merging**
